import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigations from '@/components/organisms/Navigations';
import '@/styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Safari Royale',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Navigations />
        {children}
      </body>
    </html>
  );
}
